### PR TITLE
Support for cuda 10.2

### PR DESCRIPTION
**Pull request by MarkWalter94**
Just 2 lines to add support for building with option 102 (cuda 10.2)

### CODE REVIEW

**Comment by takuya-takeuchi** [comment]
@MarkWalter94
Thank you for your contribution.
 
It is not enough.

1. Must mofiry BuildWindows.ps1, BuildUbuntu16.ps1 and BuildCentOS7.ps1 to support CUDA 10.2
2. Must mofiry TestPackageWindows.ps1, TestPackageUbuntu16.ps1 and TestPackageCentOS7.ps1 to support CUDA 10.2
3. Add dockerfile for cuda 10.2

But I have no machine which installs CUDA 10.2. I cannot test it.
And dlib may not support CUDA 10.2
https://stackoverflow.com/questions/59561171/dlib-not-using-cuda-but-have-process

**Comment by takuya-takeuchi** [comment]
Start development on https://github.com/takuya-takeuchi/DlibDotNet/tree/feature/cuda10.2
It is experimental.

**Comment by MarkWalter94** [comment]
Thanks so much, i've a pc with cuda 10.2, and i'm currently using with that configuration and seems to work fine!
Keep up the great work and thanks for the support

**Comment by takuya-takeuchi** [comment]
https://github.com/takuya-takeuchi/DlibDotNet/tree/feature/cuda10.2 was merged to develop. So this PR is closed.

**Pull request closed without merging**
