### PR TITLE
add network type 2 for mmod example

### PR DESCRIPTION
**Pull request by turowicz**
Fixing #85

### CODE REVIEW

**Comment by takuya-takeuchi** [comment]
fantastic!!! I'm glag that you understand this mess code and add new function:)
I'm busy and not able to review your code right now.
but I believe your code has no problem.

please forgive me not be able to reward your contribution right now

**Comment by turowicz** [comment]
No problem, I contribute for free!

**Comment by turowicz** [comment]
It would be nice to have that merged in next week.

**Comment by turowicz** [comment]
Added another type

**Comment by takuya-takeuchi** [comment]
@turowicz good job!!

**Pull request merged**
