### PR TITLE
[fix] Null terminate all strings passed to native code

### PR DESCRIPTION
**Pull request by LunaRyuko**
System.Text.Encoding.GetBytes doesn't return byte arrays that are null terminated (which are required for when you work with C++ code), which caused some issues when I tried using the lib for facial landmark detection. This PR should fix it.

### CODE REVIEW

**Comment by takuya-takeuchi** [comment]
@LunaRyuko 
Thank you for your contribution.
LGTM.

But I hope you work on the following task before merge your modification.

1. change branch from master to develop
1. Remove modification of *.csproj
1. Could you add new method to DlibDotNet/Util/StringHelper.cs?
   This new method accept string and Encoding instance and return byte array include null teminate.

**Comment by valerysntx** [comment]
> which caused some issues when I tried using the lib ...
Please, if possible, give more details on issues, so your PR intent could be discussed or analyzed deeply

**Comment by takuya-takeuchi** [comment]
@valerysntx 
> Marshal.StringToHGlobalAnsi(string) does the same trick... stringtohglobalansi

.NET system.string is UTF16. I guess `Marshal.StringToHGlobalAnsi` convert it to UTF8 std::string and almost character will be corrupt.

Early days, I used `Encoding.UTF8.GetBytes`. But it occurs some problem on non-alphanumeric language env.
https://github.com/takuya-takeuchi/FaceRecognitionDotNet/issues/21

dlib can not accept wstring. so we should specify encode.

> Please, if possible, give more details on issues, such we can discuss or analyze things deeply

Thank you for your good jobs. I forgot to confirm about it.

**Comment by LunaRyuko** [comment]
Thanks for the input, will do!

**Comment by takuya-takeuchi** [comment]
This PR should be closed due to #160.

**Pull request closed without merging**
